default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  pool: 5

development:
  <<: *default
  database: session_development

test:
  <<: *default
  database: session_test

staging:
  <<: *default
  database: session_development

preproduction:
  <<: *default
  database: session_development

production:
  <<: *default
  database: session_development
